version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: DockerfileDev
    ports:
      - 80:80
      - 4000:4000
    environment:
      - REACT_APP_BACKEND_ENDPOINT=${REACT_APP_BACKEND_ENDPOINT}
      - BACKEND_URL=${REACT_APP_BACKEND_ENDPOINT}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html/manage
      - ./src:/home/node/src
     
networks:
  default:
    external:
      name: shorturl_default