version: "3"
services:
  server:
    build:
      context: ./
    container_name: server
    volumes:
      - ./logs:/home/node/app/logs
      - ../client/build:/home/node/client/build
      - ./src:/home/node/server/src
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - JWT_SECRET=${JWT_SECRET}
      - IPREGISTRY_API_KEY=${IPREGISTRY_API_KEY}
    ports:
      - ${PORT}:4000
  
networks:
  default:
    external:
      name: shorturl_default